/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#bcc7de',
        'on-surface': '#1b1b1d',
        'on-background': '#1b1b1d',
        'surface-dim': '#dcd9db',
        'surface-container-highest': '#e4e2e3',
        'secondary-fixed': '#ffdad6',
        'surface-variant': '#e4e2e3',
        'secondary-container': '#ff665c',
        'on-secondary-fixed-variant': '#8e1214',
        'on-tertiary-fixed-variant': '#564427',
        'inverse-on-surface': '#f3f0f2',
        'on-primary-fixed': '#111c2d',
        background: '#fbf8fa',
        'on-primary-fixed-variant': '#3c475a',
        secondary: '#b02d29',
        'on-secondary-container': '#690007',
        'primary-fixed': '#d8e3fb',
        primary: '#091426',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'tertiary-container': '#35260c',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#bcc7de',
        'on-tertiary-fixed': '#271902',
        surface: '#fbf8fa',
        'secondary-fixed-dim': '#ffb4ac',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#ddc39d',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f5f3f4',
        'on-primary-container': '#8590a6',
        tertiary: '#1e1200',
        'surface-container-high': '#eae7e9',
        'surface-container': '#f0edef',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        'outline-variant': '#c5c6cd',
        'on-tertiary-container': '#a38c6a',
        'on-surface-variant': '#45474c',
        'on-secondary-fixed': '#410002',
        'surface-bright': '#fbf8fa',
        'inverse-surface': '#303032',
        'on-error': '#ffffff',
        'primary-container': '#1e293b',
        'surface-tint': '#545f73',
        outline: '#75777d',
        'tertiary-fixed': '#fadfb8',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        md: '24px',
        unit: '4px',
        xl: '80px',
        margin: '48px',
        gutter: '24px',
        sm: '12px',
        lg: '48px',
      },
      fontFamily: {
        'headline-lg': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
        'display-xl': ['Space Grotesk'],
        'body-md': ['Space Grotesk'],
        'body-lg': ['Space Grotesk'],
        'label-sm': ['Space Grotesk'],
      },
      fontSize: {
        'headline-lg': [
          '40px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-xl': [
          '72px',
          { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' },
        ],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': [
          '12px',
          { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' },
        ],
      },
      animation: {
        fadeIn: 'fadeIn 0.3s ease-in',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
