name: msw-prod

include:
  - docker/compose.yaml

services:
  backend:
    image: msw-backend:latest
    restart: unless-stopped

  frontend:
    image: msw-frontend:latest
    restart: unless-stopped

  mysql:
    restart: unless-stopped
