<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing services
        Service::truncate();

        $services = [
            // ===== MAINTENANCE =====
            [
                'code' => 'MAINT',
                'name' => 'Maintenance Services',
                'description' => 'Complete motorcycle maintenance and inspection services',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => null,
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'build',
                'is_active' => true,
                'sort_order' => 1,
            ],
            // Fluid Maintenance
            [
                'code' => 'MAINT_FLUID',
                'name' => 'Fluid Maintenance',
                'description' => 'Inspection and maintenance of all fluid systems',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Fluid Maintenance',
                'parent_id' => null, // Will be set based on code
                'selection_mode' => 0,
                'icon' => 'opacity',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'code' => 'MAINT_FLUID_01',
                'name' => 'Engine Oil Inspection',
                'description' => 'Check engine oil level and condition',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Fluid Maintenance',
                'parent_id' => null, // Top level item
                'selection_mode' => 1,
                'icon' => 'opacity',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'code' => 'MAINT_FLUID_02',
                'name' => 'Oil Filter Inspection',
                'description' => 'Inspect oil filter condition',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Fluid Maintenance',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'opacity',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'code' => 'MAINT_FLUID_03',
                'name' => 'Coolant Level Inspection',
                'description' => 'Check and top up coolant level',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Fluid Maintenance',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'opacity',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'code' => 'MAINT_FLUID_04',
                'name' => 'Brake Fluid Inspection',
                'description' => 'Check brake fluid level and condition',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Fluid Maintenance',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'opacity',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'code' => 'MAINT_FLUID_05',
                'name' => 'Clutch Fluid Inspection',
                'description' => 'Check clutch fluid level and condition',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Fluid Maintenance',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'opacity',
                'is_active' => true,
                'sort_order' => 15,
            ],

            // Brake System
            [
                'code' => 'MAINT_BRAKE',
                'name' => 'Brake System',
                'description' => 'Complete brake system inspection and maintenance',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Brake System',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'slow_motion_video',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'code' => 'MAINT_BRAKE_01',
                'name' => 'Brake Pad Inspection',
                'description' => 'Measure brake pad thickness',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Brake System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'slow_motion_video',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'code' => 'MAINT_BRAKE_02',
                'name' => 'Brake Disc Inspection',
                'description' => 'Inspect brake disc for wear and damage',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Brake System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'slow_motion_video',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'code' => 'MAINT_BRAKE_03',
                'name' => 'Brake Caliper Inspection',
                'description' => 'Inspect brake calipers for proper operation',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Brake System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'slow_motion_video',
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'code' => 'MAINT_BRAKE_04',
                'name' => 'Brake Control Cable Adjustment',
                'description' => 'Adjust brake cable tension',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Brake System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'slow_motion_video',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'code' => 'MAINT_BRAKE_05',
                'name' => 'Brake Control Cable Lubrication',
                'description' => 'Lubricate brake cables',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Brake System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'slow_motion_video',
                'is_active' => true,
                'sort_order' => 25,
            ],

            // Clutch System
            [
                'code' => 'MAINT_CLUTCH',
                'name' => 'Clutch System',
                'description' => 'Clutch system inspection and adjustment',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Clutch System',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'settings',
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'code' => 'MAINT_CLUTCH_01',
                'name' => 'Clutch Control Cable Inspection',
                'description' => 'Inspect clutch cable condition',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Clutch System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings',
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'code' => 'MAINT_CLUTCH_02',
                'name' => 'Clutch Control Cable Adjustment',
                'description' => 'Adjust clutch cable free play',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Clutch System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings',
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'code' => 'MAINT_CLUTCH_03',
                'name' => 'Clutch Control Cable Lubrication',
                'description' => 'Lubricate clutch cable',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Clutch System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings',
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'code' => 'MAINT_CLUTCH_04',
                'name' => 'Clutch Fluid Inspection',
                'description' => 'Check clutch hydraulic fluid',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Clutch System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings',
                'is_active' => true,
                'sort_order' => 34,
            ],

            // Suspension & Steering
            [
                'code' => 'MAINT_SUSP',
                'name' => 'Suspension & Steering',
                'description' => 'Suspension and steering system inspection',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Suspension & Steering',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'airline_seat_recline_normal',
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'code' => 'MAINT_SUSP_01',
                'name' => 'Steering Head Bearing Inspection',
                'description' => 'Check steering head bearing condition',
                'price' => 20.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Suspension & Steering',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'airline_seat_recline_normal',
                'is_active' => true,
                'sort_order' => 41,
            ],
            [
                'code' => 'MAINT_SUSP_02',
                'name' => 'Front Fork Inspection',
                'description' => 'Inspect front fork operation',
                'price' => 20.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Suspension & Steering',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'airline_seat_recline_normal',
                'is_active' => true,
                'sort_order' => 42,
            ],
            [
                'code' => 'MAINT_SUSP_03',
                'name' => 'Rear Shock Absorber Inspection',
                'description' => 'Check rear shock condition',
                'price' => 20.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Suspension & Steering',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'airline_seat_recline_normal',
                'is_active' => true,
                'sort_order' => 43,
            ],
            [
                'code' => 'MAINT_SUSP_04',
                'name' => 'Oil Leak Inspection',
                'description' => 'Check for suspension oil leaks',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Suspension & Steering',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'airline_seat_recline_normal',
                'is_active' => true,
                'sort_order' => 44,
            ],

            // Tire Service
            [
                'code' => 'MAINT_TIRE',
                'name' => 'Tire Service',
                'description' => 'Tire inspection and maintenance',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Tire Service',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'tire_repair',
                'is_active' => true,
                'sort_order' => 50,
            ],
            [
                'code' => 'MAINT_TIRE_01',
                'name' => 'Tire Pressure Inspection',
                'description' => 'Check and adjust tire pressure',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Tire Service',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'tire_repair',
                'is_active' => true,
                'sort_order' => 51,
            ],
            [
                'code' => 'MAINT_TIRE_02',
                'name' => 'Tire Wear Inspection',
                'description' => 'Measure tire tread depth',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Tire Service',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'tire_repair',
                'is_active' => true,
                'sort_order' => 52,
            ],

            // Drive System
            [
                'code' => 'MAINT_DRIVE',
                'name' => 'Drive System',
                'description' => 'Chain and belt drive inspection',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Drive System',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'settings_input_component',
                'is_active' => true,
                'sort_order' => 60,
            ],
            [
                'code' => 'MAINT_DRIVE_01',
                'name' => 'Drivetrain Tension Inspection',
                'description' => 'Check chain/belt tension',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Drive System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings_input_component',
                'is_active' => true,
                'sort_order' => 61,
            ],
            [
                'code' => 'MAINT_DRIVE_02',
                'name' => 'Drivetrain Alignment Inspection',
                'description' => 'Check chain/belt alignment',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Drive System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings_input_component',
                'is_active' => true,
                'sort_order' => 62,
            ],
            [
                'code' => 'MAINT_DRIVE_03',
                'name' => 'Drivetrain Lubrication',
                'description' => 'Clean and lubricate chain',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Drive System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings_input_component',
                'is_active' => true,
                'sort_order' => 63,
            ],

            // Battery & Charging
            [
                'code' => 'MAINT_BATT',
                'name' => 'Battery & Charging',
                'description' => 'Electrical system inspection',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Battery & Charging',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'battery_charging_full',
                'is_active' => true,
                'sort_order' => 70,
            ],
            [
                'code' => 'MAINT_BATT_01',
                'name' => 'Battery Inspection',
                'description' => 'Check battery condition and terminals',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Battery & Charging',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'battery_charging_full',
                'is_active' => true,
                'sort_order' => 71,
            ],
            [
                'code' => 'MAINT_BATT_02',
                'name' => 'Charging System Inspection',
                'description' => 'Test alternator and voltage regulator',
                'price' => 25.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Battery & Charging',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'battery_charging_full',
                'is_active' => true,
                'sort_order' => 72,
            ],

            // Lighting & Dashboard
            [
                'code' => 'MAINT_LIGHT',
                'name' => 'Lighting & Dashboard',
                'description' => 'Lighting and instrument cluster inspection',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Lighting & Dashboard',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'light_mode',
                'is_active' => true,
                'sort_order' => 80,
            ],
            [
                'code' => 'MAINT_LIGHT_01',
                'name' => 'Dashboard Inspection',
                'description' => 'Check dashboard displays and indicators',
                'price' => 15.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Lighting & Dashboard',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'light_mode',
                'is_active' => true,
                'sort_order' => 81,
            ],
            [
                'code' => 'MAINT_LIGHT_02',
                'name' => 'Indicator Inspection',
                'description' => 'Test all turn signals',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Lighting & Dashboard',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'light_mode',
                'is_active' => true,
                'sort_order' => 82,
            ],
            [
                'code' => 'MAINT_LIGHT_03',
                'name' => 'Lighting Inspection',
                'description' => 'Test headlight and taillight',
                'price' => 10.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Lighting & Dashboard',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'light_mode',
                'is_active' => true,
                'sort_order' => 83,
            ],

            // Electrical System
            [
                'code' => 'MAINT_ELEC',
                'name' => 'Electrical System',
                'description' => 'Wiring and electrical inspection',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Electrical System',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'electric_bolt',
                'is_active' => true,
                'sort_order' => 90,
            ],
            [
                'code' => 'MAINT_ELEC_01',
                'name' => 'Wire Harness Inspection',
                'description' => 'Check wiring harness condition',
                'price' => 25.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Electrical System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'electric_bolt',
                'is_active' => true,
                'sort_order' => 91,
            ],
            [
                'code' => 'MAINT_ELEC_02',
                'name' => 'Poor Contact Detection',
                'description' => 'Diagnose electrical poor contacts',
                'price' => 30.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'Electrical System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'electric_bolt',
                'is_active' => true,
                'sort_order' => 92,
            ],

            // General Maintenance
            [
                'code' => 'MAINT_GEN',
                'name' => 'General Maintenance',
                'description' => 'General lubrication and greasing',
                'price' => null,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'General Maintenance',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'handyman',
                'is_active' => true,
                'sort_order' => 100,
            ],
            [
                'code' => 'MAINT_GEN_01',
                'name' => 'General Lubrication',
                'description' => 'Lubricate all pivot points',
                'price' => 20.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'General Maintenance',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'handyman',
                'is_active' => true,
                'sort_order' => 101,
            ],
            [
                'code' => 'MAINT_GEN_02',
                'name' => 'General Greasing',
                'description' => 'Grease all bearings',
                'price' => 20.00,
                'category' => 'maintenance',
                'main_category' => 'maintenance',
                'sub_category' => 'General Maintenance',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'handyman',
                'is_active' => true,
                'sort_order' => 102,
            ],

            // ===== WASHING =====
            [
                'code' => 'WASH',
                'name' => 'Washing Services',
                'description' => 'Professional motorcycle washing and detailing',
                'price' => null,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => null,
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'wash',
                'is_active' => true,
                'sort_order' => 200,
            ],
            // Basic Wash
            [
                'code' => 'WASH_BASIC',
                'name' => 'Basic Wash',
                'description' => 'Essential exterior wash',
                'price' => null,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Basic Wash',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'wash',
                'is_active' => true,
                'sort_order' => 201,
            ],
            [
                'code' => 'WASH_BASIC_01',
                'name' => 'Full Motorcycle Wash',
                'description' => 'Complete exterior wash',
                'price' => 25.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Basic Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'wash',
                'is_active' => true,
                'sort_order' => 202,
            ],
            [
                'code' => 'WASH_BASIC_02',
                'name' => 'Foam Wash',
                'description' => 'Foam wash application',
                'price' => 30.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Basic Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'wash',
                'is_active' => true,
                'sort_order' => 203,
            ],

            // Normal Wash
            [
                'code' => 'WASH_NORMAL',
                'name' => 'Normal Wash',
                'description' => 'Standard comprehensive wash',
                'price' => null,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Normal Wash',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'verified',
                'is_active' => true,
                'sort_order' => 210,
            ],
            [
                'code' => 'WASH_NORMAL_01',
                'name' => 'Full Motorcycle Wash',
                'description' => 'Complete exterior wash',
                'price' => 25.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Normal Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'verified',
                'is_active' => true,
                'sort_order' => 211,
            ],
            [
                'code' => 'WASH_NORMAL_02',
                'name' => 'Foam Wash Detail Spray',
                'description' => 'Detail spray after foam wash',
                'price' => 15.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Normal Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'verified',
                'is_active' => true,
                'sort_order' => 212,
            ],
            [
                'code' => 'WASH_NORMAL_03',
                'name' => 'Tire Cleaning',
                'description' => 'Clean and dress tires',
                'price' => 10.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Normal Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'verified',
                'is_active' => true,
                'sort_order' => 213,
            ],
            [
                'code' => 'WASH_NORMAL_04',
                'name' => 'Chain Cleaning & Lubrication',
                'description' => 'Clean and lube chain',
                'price' => 15.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Normal Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'verified',
                'is_active' => true,
                'sort_order' => 214,
            ],
            [
                'code' => 'WASH_NORMAL_05',
                'name' => 'Sprocket Cleaning',
                'description' => 'Clean sprocket and surrounding area',
                'price' => 10.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Normal Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'verified',
                'is_active' => true,
                'sort_order' => 215,
            ],

            // Premium Wash
            [
                'code' => 'WASH_PREMIUM',
                'name' => 'Premium Wash',
                'description' => 'Full premium detailing wash',
                'price' => null,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Premium Wash',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'bolt',
                'is_active' => true,
                'sort_order' => 220,
            ],
            [
                'code' => 'WASH_PREMIUM_01',
                'name' => 'Deep Motorcycle Cleaning',
                'description' => 'Thorough deep cleaning',
                'price' => 45.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Premium Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'bolt',
                'is_active' => true,
                'sort_order' => 221,
            ],
            [
                'code' => 'WASH_PREMIUM_02',
                'name' => 'Full Motorcycle Detailing',
                'description' => 'Complete surface detailing',
                'price' => 60.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Premium Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'bolt',
                'is_active' => true,
                'sort_order' => 222,
            ],
            [
                'code' => 'WASH_PREMIUM_03',
                'name' => 'Detailed Component Cleaning',
                'description' => 'Clean detailed components',
                'price' => 35.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Premium Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'bolt',
                'is_active' => true,
                'sort_order' => 223,
            ],
            [
                'code' => 'WASH_PREMIUM_04',
                'name' => 'Hard-to-Reach Area Cleaning',
                'description' => 'Clean difficult areas',
                'price' => 25.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Premium Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'bolt',
                'is_active' => true,
                'sort_order' => 224,
            ],
            [
                'code' => 'WASH_PREMIUM_05',
                'name' => 'Premium Finishing Treatment',
                'description' => 'Apply premium finish',
                'price' => 40.00,
                'category' => 'washing',
                'main_category' => 'washing',
                'sub_category' => 'Premium Wash',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'bolt',
                'is_active' => true,
                'sort_order' => 225,
            ],

            // ===== ENGINE CHECK UP =====
            [
                'code' => 'ENGINE',
                'name' => 'Engine Check Up',
                'description' => 'Complete engine diagnosis and inspection',
                'price' => null,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => null,
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'monitor_heart',
                'is_active' => true,
                'sort_order' => 300,
            ],
            // Ignition System
            [
                'code' => 'ENGINE_IGN',
                'name' => 'Ignition System',
                'description' => 'Ignition system inspection',
                'price' => null,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Ignition System',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'flash_on',
                'is_active' => true,
                'sort_order' => 301,
            ],
            [
                'code' => 'ENGINE_IGN_01',
                'name' => 'Spark Plug Inspection & Cleaning',
                'description' => 'Check and clean spark plugs',
                'price' => 25.00,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Ignition System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'flash_on',
                'is_active' => true,
                'sort_order' => 302,
            ],

            // Air Intake System
            [
                'code' => 'ENGINE_AIR',
                'name' => 'Air Intake System',
                'description' => 'Air system inspection',
                'price' => null,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Air Intake System',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'air',
                'is_active' => true,
                'sort_order' => 310,
            ],
            [
                'code' => 'ENGINE_AIR_01',
                'name' => 'Air Filter Inspection & Cleaning',
                'description' => 'Check and clean air filter',
                'price' => 20.00,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Air Intake System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'air',
                'is_active' => true,
                'sort_order' => 311,
            ],

            // Fuel System
            [
                'code' => 'ENGINE_FUEL',
                'name' => 'Fuel System',
                'description' => 'Fuel system inspection',
                'price' => null,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Fuel System',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'ev_station',
                'is_active' => true,
                'sort_order' => 320,
            ],
            [
                'code' => 'ENGINE_FUEL_01',
                'name' => 'External Fuel Hose Inspection',
                'description' => 'Check fuel hoses',
                'price' => 15.00,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Fuel System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'ev_station',
                'is_active' => true,
                'sort_order' => 321,
            ],
            [
                'code' => 'ENGINE_FUEL_02',
                'name' => 'Fuel Filter Inspection',
                'description' => 'Check fuel filter',
                'price' => 15.00,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Fuel System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'ev_station',
                'is_active' => true,
                'sort_order' => 322,
            ],
            [
                'code' => 'ENGINE_FUEL_03',
                'name' => 'Injector Inspection & Cleaning',
                'description' => 'Check and clean fuel injectors',
                'price' => 45.00,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Fuel System',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'ev_station',
                'is_active' => true,
                'sort_order' => 323,
            ],

            // Engine Health
            [
                'code' => 'ENGINE_HEALTH',
                'name' => 'Engine Health',
                'description' => 'Engine condition inspection',
                'price' => null,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Engine Health',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'favorite',
                'is_active' => true,
                'sort_order' => 330,
            ],
            [
                'code' => 'ENGINE_HEALTH_01',
                'name' => 'Engine Cylinder Pressure Test',
                'description' => 'Test cylinder compression',
                'price' => 60.00,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Engine Health',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'favorite',
                'is_active' => true,
                'sort_order' => 331,
            ],
            [
                'code' => 'ENGINE_HEALTH_02',
                'name' => 'Engine Carbon Deposit Inspection',
                'description' => 'Check carbon buildup',
                'price' => 35.00,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Engine Health',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'favorite',
                'is_active' => true,
                'sort_order' => 332,
            ],
            [
                'code' => 'ENGINE_HEALTH_03',
                'name' => 'Oil Pump Pressure Inspection',
                'description' => 'Check oil pump pressure',
                'price' => 40.00,
                'category' => 'engine',
                'main_category' => 'engine_checkup',
                'sub_category' => 'Engine Health',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'favorite',
                'is_active' => true,
                'sort_order' => 333,
            ],

            // ===== TUNING PERFORMANCE =====
            [
                'code' => 'TUNING',
                'name' => 'Tuning Performance',
                'description' => 'Performance tuning and diagnostics',
                'price' => null,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => null,
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'speed',
                'is_active' => true,
                'sort_order' => 400,
            ],
            // Dyno Tuning
            [
                'code' => 'TUNING_DYNO',
                'name' => 'Dyno Tuning',
                'description' => 'Professional dynamometer tuning',
                'price' => null,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'Dyno Tuning',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'speed',
                'is_active' => true,
                'sort_order' => 401,
            ],
            [
                'code' => 'TUNING_DYNO_01',
                'name' => '1000cc & Above',
                'description' => 'Dyno tuning for 1000cc+ bikes',
                'price' => 450.00,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'Dyno Tuning',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'speed',
                'is_active' => true,
                'sort_order' => 402,
            ],
            [
                'code' => 'TUNING_DYNO_02',
                'name' => '600cc Class',
                'description' => 'Dyno tuning for 600cc bikes',
                'price' => 350.00,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'Dyno Tuning',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'speed',
                'is_active' => true,
                'sort_order' => 403,
            ],
            [
                'code' => 'TUNING_DYNO_03',
                'name' => '200cc–400cc Class',
                'description' => 'Dyno tuning for 200-400cc bikes',
                'price' => 250.00,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'Dyno Tuning',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'speed',
                'is_active' => true,
                'sort_order' => 404,
            ],

            // ECU Diagnostics
            [
                'code' => 'TUNING_ECU',
                'name' => 'ECU Diagnostics',
                'description' => 'Electronic control unit diagnostics',
                'price' => null,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'ECU Diagnostics',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'settings',
                'is_active' => true,
                'sort_order' => 410,
            ],
            [
                'code' => 'TUNING_ECU_01',
                'name' => 'TXB Diagnostic Tool Scan',
                'description' => 'Full system diagnostic scan',
                'price' => 50.00,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'ECU Diagnostics',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings',
                'is_active' => true,
                'sort_order' => 411,
            ],
            [
                'code' => 'TUNING_ECU_02',
                'name' => 'ECU Error Code Reading',
                'description' => 'Read and clear error codes',
                'price' => 30.00,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'ECU Diagnostics',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings',
                'is_active' => true,
                'sort_order' => 412,
            ],
            [
                'code' => 'TUNING_ECU_03',
                'name' => 'ECU Modified',
                'description' => 'ECU modification service',
                'price' => 200.00,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'ECU Diagnostics',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings',
                'is_active' => true,
                'sort_order' => 413,
            ],
            [
                'code' => 'TUNING_ECU_04',
                'name' => 'Remap',
                'description' => 'ECU remapping service',
                'price' => 300.00,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'ECU Diagnostics',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'settings',
                'is_active' => true,
                'sort_order' => 414,
            ],

            // ABS Inspection
            [
                'code' => 'TUNING_ABS',
                'name' => 'ABS Inspection',
                'description' => 'Anti-lock braking system inspection',
                'price' => null,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'ABS Inspection',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'shield',
                'is_active' => true,
                'sort_order' => 420,
            ],
            [
                'code' => 'TUNING_ABS_01',
                'name' => 'ABS System Inspection',
                'description' => 'Complete ABS diagnostic check',
                'price' => 60.00,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'ABS Inspection',
                'parent_id' => null,
                'selection_mode' => 1,
                'icon' => 'shield',
                'is_active' => true,
                'sort_order' => 421,
            ],

            // Special case for Dyno Tuning - included in every Dyno package
            [
                'code' => 'DYNO_INCLUDED',
                'name' => 'Dyno Tuning Package Inclusions',
                'description' => 'Included in every Dyno Tuning package',
                'price' => 0,
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'Dyno Tuning Package Inclusions',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'check_circle',
                'is_active' => true,
                'sort_order' => 430,
            ],
            [
                'code' => 'DYNO_INCL_01',
                'name' => 'Full Motorcycle Check-Up Service',
                'description' => 'Complete pre-dyno inspection',
                'price' => 0, // Included free
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'Dyno Tuning Package Inclusions',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'check_circle',
                'is_active' => true,
                'sort_order' => 431,
            ],
            [
                'code' => 'DYNO_INCL_02',
                'name' => 'ECU Reading & Diagnostics',
                'description' => 'ECU diagnostic check',
                'price' => 0, // Included free
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'Dyno Tuning Package Inclusions',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'check_circle',
                'is_active' => true,
                'sort_order' => 432,
            ],
            [
                'code' => 'DYNO_INCL_03',
                'name' => 'ECU Modification & Optimization',
                'description' => 'ECU tuning optimization',
                'price' => 0, // Included free
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'Dyno Tuning Package Inclusions',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'check_circle',
                'is_active' => true,
                'sort_order' => 433,
            ],
            [
                'code' => 'DYNO_INCL_04',
                'name' => 'Professional Dyno Testing and Analysis',
                'description' => 'Dyno run and data analysis',
                'price' => 0, // Included free
                'category' => 'tuning',
                'main_category' => 'tuning',
                'sub_category' => 'Dyno Tuning Package Inclusions',
                'parent_id' => null,
                'selection_mode' => 0,
                'icon' => 'check_circle',
                'is_active' => true,
                'sort_order' => 434,
            ],
        ];

        foreach ($services as $service) {
            Service::updateOrCreate(
                ['code' => $service['code']],
                $service
            );
        }
    }
}
